# Generated by Django 5.1.3 on 2024-11-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='status_movie',
            new_name='movie_status',
        ),
    ]
