# Generated by Django 5.1.3 on 2024-11-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_status_movie_movie_movie_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_trailer',
            new_name='movie_trailers',
        ),
    ]
